// Copyright (c) 2021 Gitpod GmbH. All rights reserved.
// Licensed under the GNU Affero General Public License (AGPL).
// See License-AGPL.txt in the project root for license information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: info.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type WorkspaceInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkspaceInfoRequest) Reset()         { *m = WorkspaceInfoRequest{} }
func (m *WorkspaceInfoRequest) String() string { return proto.CompactTextString(m) }
func (*WorkspaceInfoRequest) ProtoMessage()    {}
func (*WorkspaceInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{0}
}

func (m *WorkspaceInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkspaceInfoRequest.Unmarshal(m, b)
}
func (m *WorkspaceInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkspaceInfoRequest.Marshal(b, m, deterministic)
}
func (m *WorkspaceInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceInfoRequest.Merge(m, src)
}
func (m *WorkspaceInfoRequest) XXX_Size() int {
	return xxx_messageInfo_WorkspaceInfoRequest.Size(m)
}
func (m *WorkspaceInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceInfoRequest proto.InternalMessageInfo

type WorkspaceInfoResponse struct {
	// workspace_id is the workspace ID of this workspace.
	WorkspaceId string `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// instance_id is the instance ID of this workspace.
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// checkout_location is the path where we initialized the workspace content
	CheckoutLocation string `protobuf:"bytes,3,opt,name=checkout_location,json=checkoutLocation,proto3" json:"checkout_location,omitempty"`
	// workspace_location is the location of the IDE workspace
	//
	// Types that are valid to be assigned to WorkspaceLocation:
	//	*WorkspaceInfoResponse_WorkspaceLocationFile
	//	*WorkspaceInfoResponse_WorkspaceLocationFolder
	WorkspaceLocation isWorkspaceInfoResponse_WorkspaceLocation `protobuf_oneof:"workspace_location"`
	// user_home is the path to the user's home.
	UserHome string `protobuf:"bytes,6,opt,name=user_home,json=userHome,proto3" json:"user_home,omitempty"`
	// GitpodAPI provides information to reach the Gitpod server API.
	GitpodApi *WorkspaceInfoResponse_GitpodAPI `protobuf:"bytes,7,opt,name=gitpod_api,json=gitpodApi,proto3" json:"gitpod_api,omitempty"`
	// gitpod_host provides Gitpod host URL.
	GitpodHost           string   `protobuf:"bytes,8,opt,name=gitpod_host,json=gitpodHost,proto3" json:"gitpod_host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkspaceInfoResponse) Reset()         { *m = WorkspaceInfoResponse{} }
func (m *WorkspaceInfoResponse) String() string { return proto.CompactTextString(m) }
func (*WorkspaceInfoResponse) ProtoMessage()    {}
func (*WorkspaceInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1}
}

func (m *WorkspaceInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkspaceInfoResponse.Unmarshal(m, b)
}
func (m *WorkspaceInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkspaceInfoResponse.Marshal(b, m, deterministic)
}
func (m *WorkspaceInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceInfoResponse.Merge(m, src)
}
func (m *WorkspaceInfoResponse) XXX_Size() int {
	return xxx_messageInfo_WorkspaceInfoResponse.Size(m)
}
func (m *WorkspaceInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceInfoResponse proto.InternalMessageInfo

func (m *WorkspaceInfoResponse) GetWorkspaceId() string {
	if m != nil {
		return m.WorkspaceId
	}
	return ""
}

func (m *WorkspaceInfoResponse) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *WorkspaceInfoResponse) GetCheckoutLocation() string {
	if m != nil {
		return m.CheckoutLocation
	}
	return ""
}

type isWorkspaceInfoResponse_WorkspaceLocation interface {
	isWorkspaceInfoResponse_WorkspaceLocation()
}

type WorkspaceInfoResponse_WorkspaceLocationFile struct {
	WorkspaceLocationFile string `protobuf:"bytes,4,opt,name=workspace_location_file,json=workspaceLocationFile,proto3,oneof"`
}

type WorkspaceInfoResponse_WorkspaceLocationFolder struct {
	WorkspaceLocationFolder string `protobuf:"bytes,5,opt,name=workspace_location_folder,json=workspaceLocationFolder,proto3,oneof"`
}

func (*WorkspaceInfoResponse_WorkspaceLocationFile) isWorkspaceInfoResponse_WorkspaceLocation() {}

func (*WorkspaceInfoResponse_WorkspaceLocationFolder) isWorkspaceInfoResponse_WorkspaceLocation() {}

func (m *WorkspaceInfoResponse) GetWorkspaceLocation() isWorkspaceInfoResponse_WorkspaceLocation {
	if m != nil {
		return m.WorkspaceLocation
	}
	return nil
}

func (m *WorkspaceInfoResponse) GetWorkspaceLocationFile() string {
	if x, ok := m.GetWorkspaceLocation().(*WorkspaceInfoResponse_WorkspaceLocationFile); ok {
		return x.WorkspaceLocationFile
	}
	return ""
}

func (m *WorkspaceInfoResponse) GetWorkspaceLocationFolder() string {
	if x, ok := m.GetWorkspaceLocation().(*WorkspaceInfoResponse_WorkspaceLocationFolder); ok {
		return x.WorkspaceLocationFolder
	}
	return ""
}

func (m *WorkspaceInfoResponse) GetUserHome() string {
	if m != nil {
		return m.UserHome
	}
	return ""
}

func (m *WorkspaceInfoResponse) GetGitpodApi() *WorkspaceInfoResponse_GitpodAPI {
	if m != nil {
		return m.GitpodApi
	}
	return nil
}

func (m *WorkspaceInfoResponse) GetGitpodHost() string {
	if m != nil {
		return m.GitpodHost
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*WorkspaceInfoResponse) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*WorkspaceInfoResponse_WorkspaceLocationFile)(nil),
		(*WorkspaceInfoResponse_WorkspaceLocationFolder)(nil),
	}
}

type WorkspaceInfoResponse_GitpodAPI struct {
	// endpoint is the websocket URL on which the token-accessible Gitpod API is served on
	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// host is the host of the endpoint. Use this host to ask supervisor a token.
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WorkspaceInfoResponse_GitpodAPI) Reset()         { *m = WorkspaceInfoResponse_GitpodAPI{} }
func (m *WorkspaceInfoResponse_GitpodAPI) String() string { return proto.CompactTextString(m) }
func (*WorkspaceInfoResponse_GitpodAPI) ProtoMessage()    {}
func (*WorkspaceInfoResponse_GitpodAPI) Descriptor() ([]byte, []int) {
	return fileDescriptor_f140d5b28dddb141, []int{1, 0}
}

func (m *WorkspaceInfoResponse_GitpodAPI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WorkspaceInfoResponse_GitpodAPI.Unmarshal(m, b)
}
func (m *WorkspaceInfoResponse_GitpodAPI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WorkspaceInfoResponse_GitpodAPI.Marshal(b, m, deterministic)
}
func (m *WorkspaceInfoResponse_GitpodAPI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WorkspaceInfoResponse_GitpodAPI.Merge(m, src)
}
func (m *WorkspaceInfoResponse_GitpodAPI) XXX_Size() int {
	return xxx_messageInfo_WorkspaceInfoResponse_GitpodAPI.Size(m)
}
func (m *WorkspaceInfoResponse_GitpodAPI) XXX_DiscardUnknown() {
	xxx_messageInfo_WorkspaceInfoResponse_GitpodAPI.DiscardUnknown(m)
}

var xxx_messageInfo_WorkspaceInfoResponse_GitpodAPI proto.InternalMessageInfo

func (m *WorkspaceInfoResponse_GitpodAPI) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *WorkspaceInfoResponse_GitpodAPI) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*WorkspaceInfoRequest)(nil), "supervisor.WorkspaceInfoRequest")
	proto.RegisterType((*WorkspaceInfoResponse)(nil), "supervisor.WorkspaceInfoResponse")
	proto.RegisterType((*WorkspaceInfoResponse_GitpodAPI)(nil), "supervisor.WorkspaceInfoResponse.GitpodAPI")
}

func init() {
	proto.RegisterFile("info.proto", fileDescriptor_f140d5b28dddb141)
}

var fileDescriptor_f140d5b28dddb141 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0xee, 0xd2, 0x40,
	0x14, 0xc5, 0xe5, 0xff, 0x49, 0x6f, 0x35, 0xd1, 0x1b, 0x90, 0x5a, 0x4d, 0x04, 0x56, 0x24, 0x24,
	0x6d, 0xc4, 0x8d, 0x09, 0x6e, 0x60, 0xa1, 0xd4, 0xb8, 0x30, 0x75, 0x61, 0xe2, 0xa6, 0xa9, 0xed,
	0x00, 0x13, 0xca, 0xdc, 0xb1, 0x33, 0xc5, 0xa5, 0x89, 0xaf, 0xe0, 0xa3, 0xb9, 0x76, 0xe7, 0x83,
	0x98, 0x4e, 0x3f, 0x88, 0x42, 0x74, 0xd7, 0x9e, 0x7b, 0x7e, 0x33, 0x67, 0x4e, 0x2e, 0x00, 0x17,
	0x6b, 0xf2, 0x64, 0x4e, 0x9a, 0x10, 0x54, 0x21, 0x59, 0x7e, 0xe0, 0x8a, 0x72, 0xf7, 0xc9, 0x86,
	0x68, 0x93, 0x31, 0x3f, 0x96, 0xdc, 0x8f, 0x85, 0x20, 0x1d, 0x6b, 0x4e, 0x42, 0x55, 0xce, 0xf1,
	0x43, 0xe8, 0x7d, 0xa0, 0x7c, 0xa7, 0x64, 0x9c, 0xb0, 0x40, 0xac, 0x29, 0x64, 0x9f, 0x0b, 0xa6,
	0xf4, 0xf8, 0xe7, 0x25, 0xf4, 0xff, 0x1a, 0x28, 0x49, 0x42, 0x31, 0x1c, 0xc1, 0xdd, 0x2f, 0xcd,
	0x20, 0xe2, 0xa9, 0xd3, 0x19, 0x76, 0x26, 0x56, 0x68, 0xb7, 0x5a, 0x90, 0xe2, 0x53, 0xb0, 0xb9,
	0x50, 0x3a, 0x16, 0x95, 0xe3, 0xc2, 0x38, 0xa0, 0x91, 0x82, 0x14, 0xa7, 0xf0, 0x20, 0xd9, 0xb2,
	0x64, 0x47, 0x85, 0x8e, 0x32, 0x4a, 0x4c, 0x22, 0xe7, 0xd2, 0xd8, 0xee, 0x37, 0x83, 0xb7, 0xb5,
	0x8e, 0x2f, 0x60, 0x70, 0xbc, 0xb0, 0x71, 0x47, 0x6b, 0x9e, 0x31, 0xe7, 0xaa, 0x44, 0x56, 0x77,
	0xc2, 0x7e, 0x6b, 0x68, 0xa8, 0x57, 0x3c, 0x63, 0xf8, 0x12, 0x1e, 0x9d, 0x23, 0x29, 0x4b, 0x59,
	0xee, 0x5c, 0xd7, 0xec, 0xe0, 0x94, 0x35, 0x06, 0x7c, 0x0c, 0x56, 0xa1, 0x58, 0x1e, 0x6d, 0x69,
	0xcf, 0x9c, 0x1b, 0x13, 0xae, 0x5b, 0x0a, 0x2b, 0xda, 0x33, 0x7c, 0x03, 0xb0, 0xe1, 0x5a, 0x52,
	0x1a, 0xc5, 0x92, 0x3b, 0xb7, 0xc3, 0xce, 0xc4, 0x9e, 0x4d, 0xbd, 0x63, 0xed, 0xde, 0xd9, 0xf2,
	0xbc, 0xd7, 0x86, 0x59, 0xbc, 0x0b, 0x42, 0xab, 0xc2, 0x17, 0x92, 0x97, 0x75, 0xd5, 0x67, 0x6d,
	0x49, 0x69, 0xa7, 0x5b, 0xd5, 0x55, 0x49, 0x2b, 0x52, 0xda, 0x9d, 0x83, 0xd5, 0x82, 0xe8, 0x42,
	0x97, 0x89, 0x54, 0x12, 0x17, 0xba, 0xee, 0xbe, 0xfd, 0x47, 0x84, 0x2b, 0x73, 0x44, 0xd5, 0xb8,
	0xf9, 0x5e, 0xf6, 0x00, 0x4f, 0x4b, 0x98, 0x7d, 0x05, 0xbb, 0x0c, 0xf6, 0xbe, 0x8c, 0x9b, 0x30,
	0x94, 0x70, 0xef, 0x8f, 0xc0, 0x38, 0xfc, 0xc7, 0x5b, 0xcc, 0x86, 0xb8, 0xa3, 0xff, 0xbe, 0x76,
	0xec, 0x7e, 0xfb, 0xf1, 0xeb, 0xfb, 0x45, 0x0f, 0xd1, 0x3f, 0x3c, 0xf3, 0xcb, 0xf5, 0xf4, 0xdb,
	0x24, 0xcb, 0xdb, 0x8f, 0xd7, 0xde, 0x3c, 0x96, 0xfc, 0xd3, 0x8d, 0x59, 0xc4, 0xe7, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xb7, 0x61, 0x47, 0x17, 0xc0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// InfoServiceClient is the client API for InfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfoServiceClient interface {
	WorkspaceInfo(ctx context.Context, in *WorkspaceInfoRequest, opts ...grpc.CallOption) (*WorkspaceInfoResponse, error)
}

type infoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoServiceClient(cc grpc.ClientConnInterface) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) WorkspaceInfo(ctx context.Context, in *WorkspaceInfoRequest, opts ...grpc.CallOption) (*WorkspaceInfoResponse, error) {
	out := new(WorkspaceInfoResponse)
	err := c.cc.Invoke(ctx, "/supervisor.InfoService/WorkspaceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServiceServer is the server API for InfoService service.
type InfoServiceServer interface {
	WorkspaceInfo(context.Context, *WorkspaceInfoRequest) (*WorkspaceInfoResponse, error)
}

// UnimplementedInfoServiceServer can be embedded to have forward compatible implementations.
type UnimplementedInfoServiceServer struct {
}

func (*UnimplementedInfoServiceServer) WorkspaceInfo(ctx context.Context, req *WorkspaceInfoRequest) (*WorkspaceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WorkspaceInfo not implemented")
}

func RegisterInfoServiceServer(s *grpc.Server, srv InfoServiceServer) {
	s.RegisterService(&_InfoService_serviceDesc, srv)
}

func _InfoService_WorkspaceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkspaceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).WorkspaceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/supervisor.InfoService/WorkspaceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).WorkspaceInfo(ctx, req.(*WorkspaceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InfoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "supervisor.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WorkspaceInfo",
			Handler:    _InfoService_WorkspaceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "info.proto",
}
