# Copyright (c) 2020 Gitpod GmbH. All rights reserved.
# Licensed under the MIT License. See License-MIT.txt in the project root for license information.

{{ $comp := .Values.components.wsManager -}}
{{- $this := dict "root" . "gp" $.Values "comp" $comp -}}
{{- if not $comp.disabled -}}
{{- $altNames := list ( printf "%s.%s" (include "gitpod.fullname" .) .Release.Namespace ) ( printf "%s.%s.svc" "ws-manager" .Release.Namespace ) "ws-manager" "ws-manager-dev" -}}
{{- $ca := genCA "wsmanager-ca" 365 -}}

{{- $server := $comp.tls.server }}
{{- if not $server.crtFile }}
{{- $cert := genSignedCert (include "gitpod.fullname" . ) nil $altNames 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $server.secretName }}"
  labels:
    app: {{ template "gitpod.fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    checksum/checksd-config: {{ $cert.Cert | indent 2 | sha256sum }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}

---

{{- $client := $comp.tls.client }}
{{- if not $client.crtFile }}
{{- $altNames := list "registry-facade" "server" "ws-manager-bridge" "ws-scheduler" "ws-proxy" "ws-manager" -}}
{{- $cert := genSignedCert (include "gitpod.fullname" . ) nil $altNames 365 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $client.secretName }}"
  labels:
    app: {{ template "gitpod.fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    checksum/checksd-config: {{ $cert.Cert | indent 2 | sha256sum }}
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end -}}
